/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Erc20Faucet } from "./Erc20Faucet";

export class Erc20FaucetFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Erc20Faucet> {
    return super.deploy(overrides || {}) as Promise<Erc20Faucet>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Erc20Faucet {
    return super.attach(address) as Erc20Faucet;
  }
  connect(signer: Signer): Erc20FaucetFactory {
    return super.connect(signer) as Erc20FaucetFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Erc20Faucet {
    return new Contract(address, _abi, signerOrProvider) as Erc20Faucet;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061019b806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806340c10f1914610030575b600080fd5b61004361003e3660046100f7565b610055565b60405190815260200160405180910390f35b6040517f40c10f190000000000000000000000000000000000000000000000000000000081523360048201526024810182905260009073ffffffffffffffffffffffffffffffffffffffff8416906340c10f19906044016020604051808303816000875af11580156100cb573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100ef919061013c565b509092915050565b6000806040838503121561010a57600080fd5b823573ffffffffffffffffffffffffffffffffffffffff8116811461012e57600080fd5b946020939093013593505050565b60006020828403121561014e57600080fd5b8151801515811461015e57600080fd5b939250505056fea2646970667358221220b69010c17c23b83a6550ef566294d0bcd2d0ee4af91df5229f178269830006ab64736f6c634300080a0033";
