/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Erc20Faucet } from "./Erc20Faucet";

export class Erc20FaucetFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Erc20Faucet> {
    return super.deploy(overrides || {}) as Promise<Erc20Faucet>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Erc20Faucet {
    return super.attach(address) as Erc20Faucet;
  }
  connect(signer: Signer): Erc20FaucetFactory {
    return super.connect(signer) as Erc20FaucetFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Erc20Faucet {
    return new Contract(address, _abi, signerOrProvider) as Erc20Faucet;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610168806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806340c10f1914610030575b600080fd5b61004361003e3660046100d1565b610055565b60405190815260200160405180910390f35b6040516340c10f1960e01b8152336004820152602481018290526000906001600160a01b038416906340c10f19906044016020604051808303816000875af11580156100a5573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100c99190610109565b509092915050565b600080604083850312156100e457600080fd5b82356001600160a01b03811681146100fb57600080fd5b946020939093013593505050565b60006020828403121561011b57600080fd5b8151801515811461012b57600080fd5b939250505056fea26469706673582212201367481234122d8371406cea5427606e687b9edd4e39b854ddaf66f462d78f7064736f6c63430008110033";
